Integration of new API
Founntain/osuplayer pull request #180
Opened 2023-01-04 19:57 UTC by Founntain

Implementation and Integration of the new API and a ton of fixes and changes

fixes #175 
fixes #176

2023-01-04 20:11 UTC, Cesan requested changes

2023-01-04 20:11 UTC, Cesan commented on OsuPlayer.Network/API/Service/AbstractApiBase.cs
>          CancellationTokenSource = new ();
Commenting these lines out would be better as this code is currently not reachable. The TODO is explaining accordingly.

2023-01-04 20:28 UTC, Cesan commented
Btw, wont #108 be implemented with this aswell?

2023-01-04 20:29 UTC, Founntain commented
Yes you are right. Added it to the linked issues!

2023-01-04 20:31 UTC, Founntain commented
Also not forget to mention #70 can actually be started when this PR is done and published as an release

2023-01-13 09:54 UTC, Cesan approved these changes

2023-01-13 09:55 UTC, Founntain commented
@Cesan Glad that you looked over the #176 because I wasn't sure about my "fix" because is was gone. Greatful that you checked over it mate!

2023-02-03 18:04 UTC, merged